language: r
cache: packages
sudo: required
repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - devtools

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r:
  - devel

os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: change
